services:
  - type: web
    name: ai-pdf-chatbot-api
    env: docker
    plan: free
    region: oregon
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MODEL_NAME
        value: gpt-4o-mini
      - key: UPLOAD_DIR
        value: ./uploads
      - key: VECTOR_STORE_DIR
        value: ./data/vectorstore
